image: "rust:1.45"

variables:
  # This variable will ensure that the CI runner pulls in your theme from the submodule
  GIT_SUBMODULE_STRATEGY: recursive  
  # Specify the zola version you want to use here
  ZOLA_VERSION: "v0.10.1"

publish:
  # Run only on successful MERGE to master. Not on merge request.
  only:
    - master
  except:
    - merge_requests
  script:
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
      # Unpack the zola executable
    - tar -xzf zola.tar.gz
      # Execute zola build
    - ./zola build
    - cd public
      # users home directory must point to public_html
    - find . -type f -exec curl --verbose --user ${FTP_USER}@${FTP_URL}:${FTP_PASS} --ftp-create-dirs -T {} ftp://ftp.${FTP_URL}/{} \;
