# The URL the site will be built for
base_url = "https://redpoll.ai"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
build_search_index = true
generate_feeds = true
# feed_filename = "feed.xml"

taxonomies = [
	{name = "categories", paginate_by = 5, rss = true},
	{name = "authors"},
]

[markdown]
highlight_code = true
# highlight_theme = "ir-white"
highlight_theme = "dimmed-fluid"
render_emoji = true
external_links_target_blank = true
smart_punctuation = false

[extra]
# Put all your custom variables here
